<?php
// session_start();

$lang = $_GET['lang'] ?? $_SESSION['lang'] ?? 'ru';
$_SESSION['lang'] = $lang;

$translations = [
    'en' => [
        'site_title' => 'Online Store',
        'welcome_message' => 'Welcome to our store!',
        'catalog' => 'Catalog',
        'login' => 'Login',
        'register' => 'Register',
        'no_account' => 'Don\'t have an account?',
        'login_failed' => 'Invalid username or password',
        'logout' => 'Logout',
        'admin_panel' => 'Admin Panel',
         'manage_users' => 'Manage Users',
        'manage_products' => 'Manage Products',
        'total_orders' => 'Total Orders',
        'total_revenue' => 'Total Revenue',
        'active_users' => 'Active Users',
        'dashboard' => 'Dashboard',
        'language' => 'Language',
        'article' => 'Article',
        'wholesale_price' => 'Wholesale Price',
        'retail_price' => 'Retail Price',
        'quantity_per_box' => 'Quantity per Box',
        'description' => 'Description',
        'category' => 'Category',
        'title' => 'Title',
        'actions' => 'Actions',
        'confirm_password' => 'Confirm Password',
        'fill_all_fields' => 'Please fill all fields.',
        'passwords_not_match' => 'Passwords do not match.',
        'password_min_length' => 'Password must be at least 6 characters.',
        'username_taken' => 'Username is already taken.',
        'already_have_account' => 'Already have an account?',
        'auth_required' => 'You need to register to add products to cart',
        'cart' => 'Cart',
        'cart_empty' => 'Your cart is empty',
        'price' => 'Price',
        'update' => 'Update',
        'remove' => 'Remove',
        'total' => 'Total',
        'checkout' => 'Checkout',
        'not_enough_stock' => 'Not enough stock',
        'my_account' => 'My Account',
        'order_history' => 'Order History',
        'no_orders' => 'You have no orders yet',
        'order' => 'Order',
        'products' => 'Products',
        'processing' => 'Processing',
        'completed' => 'Completed',
        'canceled' => 'Canceled',
        'edit' => 'Edit',
        'edit_product' => 'Edit Product',
        'update_product' => 'Update Product',
        'current_image' => 'Current Image',
        'cancel' => 'Cancel',
        'phone' => 'Phone',
        'phone_required' => 'Phone is required',
        'manage_orders' => 'Manage Orders',
        'customer' => 'Customer',
        'date' => 'Date',
        'details' => 'Details',
        'management' => 'Management',
        'error_403' => '403 Forbidden',
        'access_denied' => 'Access Denied',
        'access_denied_description' => 'You do not have permission to view this page.',
        'back_to_home' => 'Back to Home',    

        
        
    ],
    'ru' => [
        'site_title' => 'Интернет Магазин',
        'welcome_message' => 'Добро пожаловать в наш магазин!',
        'catalog' => 'Каталог',
        'login' => 'Вход',
        'register' => 'Регистрация',
        'no_account' => 'Нет аккаунта?',
        'login_failed' => 'Неверный логин или пароль', // Добавлено
        'logout' => 'Выход',
        'admin_panel' => 'Админ Меню',
        'manage_users' => 'Управление пользователями',
        'manage_products' => 'Управление товарами',
        'total_orders' => 'Всего заказов',
        'total_revenue' => 'Итого',
        'active_users' => 'Активные пользователи',
        'dashboard' => 'Информационная панель',
        'language' => 'Язык',
         'article' => 'Артикул',
        'wholesale_price' => 'Оптовая цена',
        'retail_price' => 'Розничная цена',
        'quantity_per_box' => 'Количество в коробке',
        'description' => 'Описание',
        'category' => 'Категория',
        'title' => 'Название',
        'actions' => 'Действия',
        'confirm_password' => 'Подтвердите пароль',
        'fill_all_fields' => 'Заполните все поля.',
        'passwords_not_match' => 'Пароли не совпадают.',
        'password_min_length' => 'Пароль должен быть не менее 6 символов.',
        'username_taken' => 'Имя пользователя занято.',
        'already_have_account' => 'Уже есть аккаунт?',
        'auth_required' => 'Для добавления товаров в корзину необходимо зарегистрироваться',
        'cart' => 'Корзина',
        'cart_empty' => 'Ваша корзина пуста',
        'price' => 'Цена',
        'update' => 'Обновить',
        'remove' => 'Удалить',
        'total' => 'Итого',
        'checkout' => 'Оформить заказ',
        'not_enough_stock' => 'Недостаточно товара',
        'my_account' => 'Личный кабинет',
        'order_history' => 'История заказов',
        'no_orders' => 'У вас пока нет заказов',
        'order' => 'Заказ',
        'products' => 'Товары',
        'processing' => 'В обработке',
        'completed' => 'Завершен',
        'canceled' => 'Отменен',
        'edit' => 'Редактировать',
        'edit_product' => 'Редактировать товар',
        'update_product' => 'Обновить товар',
        'current_image' => 'Текущее изображение',
        'cancel' => 'Отмена',
        'phone' => 'Телефон',
        'phone_required' => 'Телефон обязателен',
        'manage_orders' => 'Управление заказами',
        'customer' => 'Покупатель',
        'date' => 'Дата',
        'details' => 'Подробности',
        'management' => 'Управление',
        'error_403' => '403 Запрещено',
        'access_denied' => 'Доступ запрещен',
        'access_denied_description' => 'У вас нет прав для просмотра этой страницы.',
        'back_to_home' => 'На главную',
    ]
];

function t($key) {
    global $lang, $translations;
    return $translations[$lang][$key] ?? $key;
}
?>